environment: SIT
appName: python-web-app
labels:
  app: python-web-app
  environment: SIT
selectorLabels:
  app: python-web-app
  environment: SIT
deployment:
  image: python-web-app
  resources:
    memory:
      request: "1920M"
      limit: "1920M"
    cpu:
      request: "0.3"
      limit: "1.0"
replicaCount: 1
service:
  type: ClusterIP
  port: 80
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: abc.successeduhub.online
      paths: 
        - /blinkapp/blink/
  tls: []